In [3]:
#importing numpy
import numpy

In [4]:
import numpy as np

In [6]:
# how list is different from numpy array
a =[ 1,6,4,8,3]
print (a *3)
b = np.array([1,6,4,8,3])
print (b*3) # here each element is multiplied by 3 of an array

[1, 6, 4, 8, 3, 1, 6, 4, 8, 3, 1, 6, 4, 8, 3]
[ 3 18 12 24  9]


In [10]:
#reshaping 
b = np.arange(1,21)
b.reshape(5,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [15]:
# 2-D array
c = np.array([[1,3,5,2],[1,5,3,7],[2,5,1,8]])
c

array([[1, 3, 5, 2],
       [1, 5, 3, 7],
       [2, 5, 1, 8]])

In [18]:
#declaring array data type
d = np.array([1,34,23.567,200] , dtype = 'int8')
print(d*2)
a = d.astype("float32")
print(a*2)


[   2   68   46 -112]
[   2.   68.   46. -112.]


In [20]:
#splicing and indexing
a = np.arange(14)
b = a[3:9]
b[0] = 87493
print(a)
print(b)
print(a[3:9])
print(a[:9])
print(a[:])
print(a[::2])
print()

[    0     1     2 87493     4     5     6     7     8     9    10    11
    12    13]
[87493     4     5     6     7     8]
[87493     4     5     6     7     8]
[    0     1     2 87493     4     5     6     7     8]
[    0     1     2 87493     4     5     6     7     8     9    10    11
    12    13]
[ 0  2  4  6  8 10 12]



In [25]:
c = np.arange(24).reshape(2, 3, 4)

print(c[0,:,:])
print(c[0])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [29]:
#shape and transpose
a = np.arange(24,34)
b= a.reshape(2,5)
print(a.shape)
print(b.shape) #shape method prints the dimention of the array

(10,)
(2, 5)


In [30]:
#transpose of a matrix
print(a.T.shape,a.shape) # transpose of a vector is vector itself
print(b.T.shape,b.shape) 

(10,) (10,)
(5, 2) (2, 5)


In [31]:
c = np.arange(24).reshape(6,4)
print(c)
print(c.T)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[ 0  4  8 12 16 20]
 [ 1  5  9 13 17 21]
 [ 2  6 10 14 18 22]
 [ 3  7 11 15 19 23]]


In [32]:
#MASKING IN NUMPY IS SIMILAR TO FILTERING
a = np.arange(35)
print(a>25)
print(a[a>25])

[False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False  True  True  True  True  True  True  True  True  True]
[26 27 28 29 30 31 32 33 34]


In [38]:
#masking in 2d array
b=np.arange(35).reshape(7,5)
print(b[b>20])

[21 22 23 24 25 26 27 28 29 30 31 32 33 34]


In [41]:
#special array
print(np.zeros(6))
print(np.ones(6))
print(np.zeros((3,4)))

[0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1.]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [43]:
np.empty((2,2))

array([[9.77979413e-312, 9.78001215e-312],
       [9.78001218e-312, 9.77978539e-312]])

In [45]:
print(np.eye(2))
print(np.identity(3))

[[1. 0.]
 [0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [47]:
#linspace command will create an array of 9 element between 1 and 6
np.linspace(1,6,9)

array([1.   , 1.625, 2.25 , 2.875, 3.5  , 4.125, 4.75 , 5.375, 6.   ])

In [49]:
#AXIS
a = np.arange(14)
print(a.sum())
b = a.reshape(7,2)
print(b.sum())
#sum()  will give the sum no matter what the dimension is

91
91


In [51]:
#performing sum across the specific dimention 
print(b.sum(axis=0)) # summing through the coloumns
print(b.sum(axis = 1)) # summing through the rows

[42 49]
[ 1  5  9 13 17 21 25]


In [52]:
#STATISTICAL ANALYSIS
#calculate maximum
b = np.arange(15).reshape(3, 5)
print(b)
print(b.max(axis=1)) # collapses all the columns
print(np.max(b, axis=1)) # prefer this way of writing


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[ 4  9 14]
[ 4  9 14]


In [53]:
#calculate mean
print(b.mean()) # gives the overall mean
print(b.mean(axis=0)) # finds column-wise mean, counter-intuitive
print(b.mean(axis=1)) # finds row-wise mean

7.0
[5. 6. 7. 8. 9.]
[ 2.  7. 12.]


In [55]:
#calculate median
np.median(b) # b.median will  give error
np.std(b)

4.320493798938574

In [56]:
#Random Uniform Distributions
np.random.rand(5)
print(90 + np.random.rand(2, 3)*10)
print(np.random.randint(50, 60, 5)) # gives integer

[[99.47556776 95.96856718 99.78805177]
 [97.36276742 96.29491274 95.82190181]]
[50 52 55 52 55]


In [59]:
#Random normal distribution
mu = 100
sigma = 15
s = np.random.normal(mu,sigma,100) # generates 100 values
print(s)
print(np.median(s))
print(np.mean(s))

[103.39147828  79.68573543  94.48881831 102.83521085  95.56262767
 112.81603357  83.29619263  89.217209    99.1365446  120.69683547
 104.12438096  59.77004175  82.35303205 123.02595976  77.29503241
  96.61607498 106.74782583 102.06474714 106.98816507  85.60125318
 113.64022866 120.53990748 125.71034614 102.74337407 102.66657289
 114.90199148 103.97618442 119.44480536 114.25913446 101.97344564
 112.56094308 135.42775856  73.26501203  92.87369843  88.77932076
  91.34738163  84.06314666  89.53979085 115.02275599  82.51123448
  72.8278262   92.75496875 115.0477676  125.71879444 115.18942801
 101.44870926  82.2756665  115.34503379 109.57103451  88.06434168
 111.30454132 101.16738054 106.43435349  99.61568127 107.80525453
 108.11263435  89.94079231 109.67826632  85.23257953  92.69146083
 106.45162912 116.53765737  76.6416303   97.33882912  84.78940373
  79.46725324 113.19037185  93.18443274 111.3219138   87.06183798
 121.9683212  103.16196105 127.03191551  64.52976238  78.77102275
 100.63984

In [65]:
#sorting
d = np.random.randint(1,9,(3,4))
print(d)
d.sort()
print(d)

[[2 7 1 1]
 [1 4 5 2]
 [4 7 6 4]]
[[1 1 2 7]
 [1 2 4 5]
 [4 4 6 7]]
